# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: demo-app
  namespace: {{ .Release.Namespace }}
spec:
  sso: 
    - name: {{ .Values.uds.sso.name }}
      clientId: {{ .Values.uds.sso.clientId }}
      redirectUris:
        - "https://{{ .Values.uds.host }}.{{ .Values.domain }}/oauth2/callback"
      enableAuthserviceSelector:
        {{- include "compat.selectorLabels" . | nindent 8 }}
      groups:
        anyOf:
          - "/UDS Core/Admin"
  network:
    serviceMesh:
      mode: ambient
    expose:
      - service: demo-app
        podLabels:
          app: demo-app
        gateway: tenant
        host: demo-app
        port: 8000
        targetPort: 8000
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Egress
        remoteGenerated: IntraNamespace

      - direction: Egress
        remoteGenerated: KubeAPI

      - direction: Egress
        selector:
          {{- include "compat.selectorLabels" . | nindent 10 }}
        remoteNamespace: keycloak
        remoteSelector:
          app.kubernetes.io/name: keycloak
        port: 8080
        description: "SSO - App to Keycloak"

      - direction: Egress
        selector:
          {{- include "compat.selectorLabels" . | nindent 10 }}
        remoteNamespace: authservice
        remoteSelector:
          app.kubernetes.io/name: authservice
        port: 10003
        description: "SSO - App to Authservice"