# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

variables:
  core-identity-authorization:
    INSECURE_ADMIN_PASSWORD_GENERATION: true
