# This is the default empty contract
apiVersion: chainloop.dev/v1
kind: Contract
metadata:
  name: default-contract
spec:
  materials:
    - name: zarf-package
      type: ARTIFACT
      skip_upload: true
    - name: zarf-definition
      type: ARTIFACT
    - name: tool-metadata
      type: ARTIFACT
    - name: zarf-aggregate-checksum
      type: STRING