name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-package-vouch-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: UDS CLI Setup
        uses: ./.github/actions/uds-cli-setup
      
      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.0.0

      - name: OLM CLI Setup
        uses: ./.github/actions/olm-cli-setup
        with:
          username: ${{ secrets.OLM_USER_ID }}
          password: ${{ secrets.OLM_PASSWORD }}

      - name: Install Ruff
        run: pip install ruff==0.15.1

      - name: Install OpenGrep
        run: |
          curl -sSL https://raw.githubusercontent.com/opengrep/opengrep/v1.15.1/install.sh | bash
          echo "$HOME/.opengrep/cli/latest" >> "$GITHUB_PATH"

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.30.0/gitleaks_8.30.0_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -zxf gitleaks.tar.gz
          mkdir -p $HOME/.local/bin
          mv gitleaks $HOME/.local/bin
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          rm gitleaks.tar.gz

      - name: Witness Run Gitleaks
        uses: testifysec/witness-run-action@7aa15e327829f1f2a523365c564c948d5dde69dd # v0.3.3
        with:
          step: gitleaks
          enable-archivista: false
          enable-sigstore: true
          command: gitleaks dir . --report-format sarif --report-path gitleaks.sarif.json
          outfile: gitleaks-witness.json

      #- name: Witness Run OpenGrep
      #  uses: testifysec/witness-run-action@7aa15e327829f1f2a523365c564c948d5dde69dd # v0.3.3
      #  with:
      #    step: opengrep
      #    enable-archivista: false
      #    enable-sigstore: true
      #    command: opengrep scan --sarif --sarif-output opengrep.sarif.json
      #    outfile: opengrep-witness.json

      - name: Run OpenGrep without Witness (due to performance issues)
        run: opengrep scan --sarif --sarif-output opengrep.sarif.json

      - name: Witness Run Ruff
        uses: testifysec/witness-run-action@7aa15e327829f1f2a523365c564c948d5dde69dd # v0.3.3
        with:
          step: ruff
          enable-archivista: false
          enable-sigstore: true
          command: ruff check app/
          outfile: ruff-witness.json

      - name: Witness Build Zarf package
        uses: testifysec/witness-run-action@7aa15e327829f1f2a523365c564c948d5dde69dd # v0.3.3
        with:
          step: zarf-create
          enable-archivista: false
          enable-sigstore: true
          command: uds zarf package create . --confirm --no-progress --architecture="amd64" --flavor "upstream"
          outfile: zarf-create-witness.json

      - name: Get GitHub OIDC token
        id: oidc
        run: |
          TOKEN="$(curl -fsSL \
            -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=fulcio" \
            | jq -r '.value')"
          echo "::add-mask::${TOKEN}"
          echo "token=${TOKEN}" >> "${GITHUB_OUTPUT}"

      - name: Vouch for Zarf Package
        env:
          OLM_CAT: cat.uds.run
          OLM_ORG: uds-army-demo
        run: |
          ./olm vouch zarf-package-*.tar.zst --identity-token "${{ steps.oidc.outputs.token }}" --sarif-evidence opengrep.sarif.json,gitleaks.sarif.json --log-level debug --test-directory tests --attestations zarf-create-witness.json,gitleaks-witness.json,ruff-witness.json

      - name: Publish Zarf Package
        run: |
          uds zarf tools registry login -u ${{ secrets.DEMO_ORG_USER_ID }} -p ${{ secrets.DEMO_ORG_PASSWORD }} registry.uds.run
          uds zarf package publish zarf-package-*.tar.zst oci://registry.uds.run/uds-army-demo
