name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-package-vouch-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: UDS CLI Setup
        uses: ./.github/actions/uds-cli-setup
      
      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.0.0
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Dockerfile
        uses: docker/build-push-action@v4
        id: build-and-push
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
      
      - name: Sign image with a key
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ghcr.io/${{ github.repository }}:latest

      - name: OLM CLI Setup
        uses: ./.github/actions/olm-cli-setup
        with:
          username: ${{ secrets.OLM_USER_ID }}
          password: ${{ secrets.OLM_PASSWORD }}

      - name: Build Zarf package
        run: |
          uds run build-zarf-package

      - name: Vouch for Zarf Package
        env:
          OLM_TOKEN: ${{ secrets.OLM_TOKEN }}
          OLM_CONTROL_PLANE: attest-cp.uds.run:443
          OLM_CAS_SERVER: attest-cas.uds.run:443
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
          ./olm vouch zarf-package-*.tar.zst --key cosign.key --log-level debug

      - name: Publish Zarf Package
        run: |
          uds zarf tools registry login -u ${{ secrets.DEMO_ORG_USER_ID }} -p ${{ secrets.DEMO_ORG_PASSWORD }} registry.uds.run
          uds zarf package publish zarf-package-*.tar.zst oci://registry.uds.run/uds-army-demo
